title: Aidan O'Gara
description: AI DPhil student at Oxford University and AI grantmaker at Longview Philanthropy
url: "https://aidanogara.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty